Repository knative-extensions/sample-controller, pull requests merged in 2019-12, with the labels that each got.

#155 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/client/injection/client/client.go
  vendor/knative.dev/pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
Labels: approved, lgtm, size/L

#156 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/const.go
  vendor/knative.dev/pkg/apis/duck/interface.go
  vendor/knative.dev/pkg/apis/duck/unstructured.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/testing/duck/doc.go
  vendor/knative.dev/pkg/testing/duck/register.go
  vendor/knative.dev/pkg/testing/duck/testbindable.go
  vendor/knative.dev/pkg/testing/duck/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/webhook/psbinding/README.md
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/doc.go
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XXL

#157 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/webhook/psbinding/README.md
Labels: approved, lgtm, size/M

#135 Update pkg and OpenCensus SD exporter versions
  Gopkg.lock
  Gopkg.toml
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_batcher.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_proto.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_test_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/aws_identity_doc_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/gcp_metadata_config.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/trace.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/monitored_resources_serving.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
Labels: approved, lgtm, size/XXL

#159 Updating pkg to latest for 0.11 release.
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#161 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, lgtm, size/S

#162 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#164 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, size/M

#172 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
Labels: approved, lgtm, size/XL

#174 Adding a git ignore file.
  .gitignore
Labels: approved, lgtm, size/S

#176 Update usage of ducks to v1.
  Gopkg.lock
  pkg/apis/samples/v1alpha1/addressable_service_types.go
  pkg/apis/samples/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/addressableservice/addressableservice.go
Labels: approved, lgtm, size/S

#177 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, lgtm, size/M

#179 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/gke/request.go
Labels: approved, lgtm, size/S

#180 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/test/gke/fake/credentials.json
  vendor/knative.dev/pkg/test/spoof/spoof.go
Labels: approved, lgtm, size/M

#181 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/fake/fake.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
Labels: approved, lgtm, size/M
