Repository knative-extensions/sample-controller, pull requests merged in 2019-11, with the labels that each got.

#136 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/v1alpha1/doc.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/cloudevents/README.md
  vendor/knative.dev/pkg/cloudevents/builder.go
  vendor/knative.dev/pkg/cloudevents/client.go
  vendor/knative.dev/pkg/cloudevents/doc.go
  vendor/knative.dev/pkg/cloudevents/encoding_binary.go
  vendor/knative.dev/pkg/cloudevents/encoding_structured.go
  vendor/knative.dev/pkg/cloudevents/event.go
  vendor/knative.dev/pkg/cloudevents/event_v01.go
  vendor/knative.dev/pkg/cloudevents/event_v02.go
  vendor/knative.dev/pkg/cloudevents/handler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hack/verify-codegen.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_eventing.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/ghutil/fakeghutil/fakeghutil.go
  vendor/knative.dev/pkg/test/gke/client.go
  vendor/knative.dev/pkg/test/gke/wait.go
  vendor/knative.dev/pkg/test/helpers/dryrun.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/test_util.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/tracker/doc.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XXL

#137 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/webhook/README.md
Labels: approved, lgtm, size/M

#138 add config validation webhook to sample-controller
  cmd/webhook/main.go
  config/200-clusterrole.yaml
  config/500-webhook-configuration.yaml
  config/webhook.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#133 Split apart defaulting and validation webhooks
  Gopkg.lock
  cmd/webhook/main.go
  config/500-webhook-configuration.yaml
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/interface.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL

#140 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/e2e_flags.go
Labels: approved, lgtm, size/S

#143 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/websocket/connection.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, lgtm, size/L

#142 remove new line in README
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#148 Format markdown
  README.md
Labels: approved, lgtm, size/XS

#149 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/read_results.sh
Labels: approved, lgtm, size/L

#151 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/binding_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/conditions/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/podspecable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/podspecable/podspecable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/source/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/source/source.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/addressable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/binding/binding.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/binding/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/conditions/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/legacytargetable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/legacytargetable/legacytargetable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/targetable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/targetable/targetable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/addressable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/conditions/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/source/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/source/source.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeduck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/ducks.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
Labels: approved, lgtm, size/XXL
