Repository knative-extensions/sample-controller, pull requests merged in 2019-07, with the labels that each got.

#38 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/limitrange/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/limitrange/limitrange.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/resourcequota/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/resourcequota/resourcequota.go
Labels: approved, lgtm, ok-to-test, size/L

#39 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
Labels: approved, lgtm, ok-to-test, size/M

#42 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/L

#43 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/webhook/user_info.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/M

#45 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/volatile_time.go
Labels: approved, lgtm, ok-to-test, size/XS

#50 Update to latest PKG with opencensus pins.
  Gopkg.lock
  Gopkg.toml
  vendor/cloud.google.com/go/container/apiv1/cluster_manager_client.go
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/contrib.go.opencensus.io/exporter/prometheus/LICENSE
  vendor/contrib.go.opencensus.io/exporter/prometheus/prometheus.go
  vendor/contrib.go.opencensus.io/exporter/prometheus/sanitize.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/gcp_metadata_config.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/monitored_resources.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/trace_proto.go
  vendor/contrib.go.opencensus.io/resource/AUTHORS
  vendor/contrib.go.opencensus.io/resource/resourcekeys/const.go
  vendor/go.opencensus.io/exporter/prometheus/prometheus.go
  vendor/go.opencensus.io/metric/metricdata/exemplar.go
  vendor/go.opencensus.io/metric/metricdata/label.go
  vendor/go.opencensus.io/metric/metricdata/metric.go
  vendor/go.opencensus.io/metric/metricexport/doc.go
  vendor/go.opencensus.io/metric/metricexport/export.go
  vendor/go.opencensus.io/metric/metricexport/reader.go
  vendor/go.opencensus.io/plugin/ocgrpc/client.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_stats_handler.go
  vendor/go.opencensus.io/plugin/ocgrpc/server.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_stats_handler.go
  vendor/go.opencensus.io/plugin/ocgrpc/stats_common.go
  vendor/go.opencensus.io/plugin/ocgrpc/trace_common.go
  vendor/go.opencensus.io/plugin/ochttp/server.go
  vendor/go.opencensus.io/stats/record.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/go.opencensus.io/tag/key.go
  vendor/go.opencensus.io/tag/map.go
  vendor/go.opencensus.io/tag/map_codec.go
  vendor/go.opencensus.io/tag/metadata.go
  vendor/go.opencensus.io/tag/profile_19.go
  vendor/google.golang.org/genproto/googleapis/container/v1/cluster_service.pb.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/tracing/opencensus.go
Labels: approved, lgtm, size/XXL

#51 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
Labels: approved, lgtm, ok-to-test, size/M

#52 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/ptr/ptr.go
Labels: approved, lgtm, ok-to-test, size/L

#53 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/knative.dev/pkg/cloudevents/event.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/kmeta/accessor.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/signals/signal.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/L

#54 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/metadata_validation.go
  vendor/knative.dev/pkg/webhook/user_info.go
Labels: approved, lgtm, ok-to-test, size/M

#55 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/knative.dev/pkg/configmap/store.go
Labels: approved, lgtm, ok-to-test, size/S

#56 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
Labels: approved, lgtm, ok-to-test, size/S

#57 Use knative.dev/test-infra
  Gopkg.lock
  Gopkg.toml
  hack/update-deps.sh
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/tools/dep-collector/README.md
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
  vendor/knative.dev/test-infra/tools/dep-collector/main.go
Labels: approved, lgtm, size/M
