Repository knative-extensions/sample-controller, pull requests merged in 2020-09, with the labels that each got.

#325 Add linting config.
  .golangci.yaml
Labels: approved, cla: yes, lgtm, size/S

#324 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#323 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#328 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#329 enable code coverage
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#330 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#331 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#332 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#334 [master] Update GitHub Actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#335 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#337 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#338 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#339 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#340 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#341 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/metrics/workqueue.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#342 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M
