Repository knative-extensions/sample-controller, pull requests merged in 2020-01, with the labels that each got.

#182 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/README.md
Labels: approved, lgtm, size/S

#183 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
Labels: approved, lgtm, size/M

#184 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_serving.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/get.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/main.go
  vendor/knative.dev/pkg/version/version.go
Labels: approved, lgtm, size/L

#186 update boilerplate to use 2020
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.sh.txt
  pkg/apis/samples/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/samples/v1alpha1/addressableservice.go
  pkg/client/clientset/versioned/typed/samples/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/samples/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/samples/v1alpha1/fake/fake_addressableservice.go
  pkg/client/clientset/versioned/typed/samples/v1alpha1/fake/fake_samples_client.go
  pkg/client/clientset/versioned/typed/samples/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/samples/v1alpha1/samples_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/samples/interface.go
  pkg/client/informers/externalversions/samples/v1alpha1/addressableservice.go
  pkg/client/informers/externalversions/samples/v1alpha1/interface.go
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  pkg/client/injection/informers/factory/factory.go
  pkg/client/injection/informers/factory/fake/fake.go
  pkg/client/injection/informers/samples/v1alpha1/addressableservice/addressableservice.go
  pkg/client/injection/informers/samples/v1alpha1/addressableservice/fake/fake.go
  pkg/client/listers/samples/v1alpha1/addressableservice.go
  pkg/client/listers/samples/v1alpha1/expansion_generated.go
Labels: approved, lgtm, size/XS

#188 Integrating the usage of the new reconciler.Event object.
  pkg/reconciler/addressableservice/addressableservice.go
Labels: approved, lgtm, size/M

#189 cleannup: break apart reconciler from custom reconciler code.
  pkg/reconciler/addressableservice/addressableservice.go
Labels: approved, lgtm, size/XS

#191 golang format tools
  pkg/reconciler/addressableservice/addressableservice.go
Labels: approved, lgtm, size/XS

#192 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/profiling/server.go
Labels: approved, lgtm, size/M

#194 Auto-update dependencies
  Gopkg.lock
  vendor/contrib.go.opencensus.io/exporter/ocagent/LICENSE
  vendor/contrib.go.opencensus.io/exporter/ocagent/common.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/connection.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/nodeinfo.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_spans.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/version.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1/metrics_service.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1/metrics_service.pb.gw.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.gw.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1/trace.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1/trace_config.pb.go
  vendor/github.com/golang/protobuf/descriptor/descriptor.go
  vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_json.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler_registry.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto2_convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/LICENSE
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/trie.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/network/prober/prober.go
  vendor/knative.dev/pkg/test/gke/endpoint.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/main.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, lgtm, size/XXL

#195 Updating pkg to latest for 0.12 release.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/configmap/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/gke/endpoint.go
Labels: approved, lgtm, size/L

#190 Break apart custom impl from reconciler boilerplate
  pkg/reconciler/addressableservice/addressableservice.go
  pkg/reconciler/addressableservice/reconciler.go
Labels: approved, lgtm, size/L

#197 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, lgtm, size/XS

#198 Updating pkg to master post 0.12 release.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/junit/junit.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/testutils/junithelper/README.md
  vendor/knative.dev/pkg/testutils/junithelper/main.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#199 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/convert.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
Labels: approved, lgtm, size/M

#201 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
Labels: approved, lgtm, size/M

#202 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
Labels: approved, lgtm, size/S

#203 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/test/mako/alerter/alerter.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, lgtm, size/M

#204 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, lgtm, size/XXL

#205 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#206 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark1/cluster.yaml
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/README.md
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, lgtm, size/M
