Repository knative-extensions/sample-controller, pull requests merged in 2020-06, with the labels that each got.

#283 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#285 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#284 Update go.mod to specify the module is go1.14
  go.mod
Labels: approved, cla: yes, lgtm, size/XS

#286 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#288 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#290 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#291 Leverage the KRShape feature in gen-reconciler for sample-controller
  pkg/apis/samples/v1alpha1/addressable_service_lifecycle.go
  pkg/apis/samples/v1alpha1/addressable_service_types.go
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/reconciler/addressableservice/addressableservice.go
Labels: approved, cla: yes, lgtm, size/M

#293 Update sample with comments / nits
  DEVELOPMENT.md
  pkg/apis/samples/v1alpha1/addressable_service_lifecycle.go
  pkg/apis/samples/v1alpha1/addressable_service_types.go
Labels: approved, cla: yes, lgtm, size/S

#292 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/testing.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#297 update-deps for sample-controller
  DEVELOPMENT.md
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#294 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/leaderelection/ordinal.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#298 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/.travis.yml
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
  vendor/github.com/kelseyhightower/envconfig/README.md
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/go.mod
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/leaderelection/ordinal.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL
