Repository knative-extensions/sample-controller, pull requests merged in 2020-07, with the labels that each got.

#299 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#301 Remove configmap volume mounts
  config/controller.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#303 Raise the terminationGracePeriod on the webhook
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#302 Add leader-election config
  config/200-clusterrole.yaml
  config/config-leader-election.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#306 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.mod
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#307 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#308 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/state.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#309 Remove the reconciled event, it is not really useful
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/stub/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/stub/reconciler.go
  pkg/reconciler/addressableservice/addressableservice.go
Labels: approved, cla: yes, lgtm, size/XS

#310 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm64.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#311 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
  vendor/knative.dev/pkg/apis/duck/proxy.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/controller/helper.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#312 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/state.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
