Repository knative-extensions/sample-controller, pull requests merged in 2020-05, with the labels that each got.

#278 Pull in pkg and add probes
  config/webhook.yaml
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#279 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/utils.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#281 Fix update-codegen for the post-go-mod world.
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS
