Repository knative-extensions/sample-controller, pull requests merged in 2020-03, with the labels that each got.

#235 Format markdown
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#236 Auto-update dependencies
  Gopkg.lock
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/testdata/README.md
  vendor/knative.dev/pkg/metrics/testdata/client-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/client-key.pem
  vendor/knative.dev/pkg/metrics/testdata/server-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/server-key.pem
Labels: approved, lgtm, size/XXL

#237 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, lgtm, size/S

#238 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/hack/update-deps.sh
Labels: approved, lgtm, size/S

#239 Fix the links in DEVELOPMENT.md too
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#240 Format markdown
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#242 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/reconciler/testing/context.go
Labels: approved, lgtm, size/M

#243 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
Labels: approved, lgtm, size/S

#244 Add missing license logic to template
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/LICENSE
  cmd/controller/kodata/VENDOR-LICENSE
  cmd/controller/kodata/refs
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/refs
  hack/update-deps.sh
  third_party/VENDOR-LICENSE
Labels: approved, lgtm, size/XXL

#245 Use ko's strict mode for better errors messages
  config/controller.yaml
  config/webhook.yaml
Labels: approved, lgtm, size/XS

#247 Modify symbolic link for LICENSE in kodata
  cmd/controller/kodata/LICENSE
  cmd/webhook/kodata/LICENSE
Labels: approved, lgtm, needs-ok-to-test, size/XS

#248 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/exporter.go
Labels: approved, lgtm, size/XS

#249 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/factory.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/prow/env.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#250 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#251 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#252 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
Labels: approved, cla: yes, lgtm, size/M

#253 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#254 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
Labels: approved, cla: yes, lgtm, size/M

#255 Fix presubmit test argument passing
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#257 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/kvstore/kvstore.go
  vendor/knative.dev/pkg/kvstore/kvstore_cm.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#260 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L
