Repository knative-extensions/sample-controller, pull requests merged in 2020-12, with the labels that each got.

#372 Move comments closer to the types they're supposed for
  pkg/apis/samples/v1alpha1/addressable_service_types.go
Labels: approved, cla: yes, lgtm, size/S

#373 Use a newer leaderelection config to reflect changes
  config/config-leader-election.yaml
Labels: approved, cla: yes, lgtm, size/S

#374 Fix license headers to be correct and consistent
  hack/tools.go
  pkg/apis/samples/v1alpha1/addressable_service_defaults.go
  pkg/apis/samples/v1alpha1/addressable_service_lifecycle.go
  pkg/apis/samples/v1alpha1/addressable_service_types.go
  pkg/apis/samples/v1alpha1/addressable_service_validation.go
  pkg/apis/samples/v1alpha1/register.go
  pkg/apis/samples/v1alpha1/register_test.go
Labels: approved, cla: yes, lgtm, size/S

#375 Widen the golangci-lint checks
  .golangci.yaml
Labels: approved, cla: yes, lgtm, size/XS

#376 Apply security best-practices to the deployments
  config/controller.yaml
  config/webhook.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#377 Add TOC to OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#378 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#380 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#381 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
