Repository knative-extensions/sample-controller, pull requests merged in 2021-03, with the labels that each got.

#404 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#405 Make a benign edit to test CODEOWNERS
  pkg/reconciler/addressableservice/addressableservice.go
Labels: approved, cla: yes, lgtm, size/XS

#406 Consolidate lines in CODEOWNERS, drop hack/test
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#407 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#408 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#409 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#410 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#411 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#412 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#413 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#414 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#415 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#417 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#418 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#419 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#420 update Simple wrong
  pkg/apis/samples/v1alpha1/simple_deployment_lifecycle.go
  pkg/apis/samples/v1alpha1/simple_deployment_types.go
Labels: approved, cla: yes, lgtm, size/S

#422 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/schema/commands/commands.go
  vendor/knative.dev/hack/schema/schema/generate_schema.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#423 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#424 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#425 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/README.md
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
