Repository knative-extensions/sample-controller, pull requests merged in 2021-08, with the labels that each got.

#491 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#492 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#494 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#495 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, cla: yes

#498 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/samples/v1alpha1/addressableservice/addressableservice.go
  pkg/client/injection/informers/samples/v1alpha1/addressableservice/filtered/addressableservice.go
  pkg/client/injection/informers/samples/v1alpha1/simpledeployment/filtered/simpledeployment.go
  pkg/client/injection/informers/samples/v1alpha1/simpledeployment/simpledeployment.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/dynamicclient/dynamicclient.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, cla: yes

#499 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved, cla: yes

#500 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#501 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/controller.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#503 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#504 Use the `controller.Impl` tracker
  pkg/reconciler/addressableservice/controller.go
  pkg/reconciler/simpledeployment/controller.go
Labels: size/S, lgtm, approved, cla: yes, kind/cleanup

#505 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#510 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes
