Repository knative-extensions/sample-controller, pull requests merged in 2021-09, with the labels that each got.

#511 [release-0.25] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#512 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#513 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#514 [release-0.24] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#516 [release-0.23] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#515 [release-0.22] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#517 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#518 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#520 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/state.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/state.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#521 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#522 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/reconciler.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, cla: yes

#519 Use a more conservative RBAC profile for sample-controller.
  config/200-clusterrole.yaml
  config/200-role.yaml
  config/201-rolebinding.yaml
Labels: lgtm, approved, size/L, cla: yes, kind/cleanup

#524 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#523 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#526 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, lgtm, approved, cla: yes

#525 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, cla: yes

#527 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved, cla: yes

#528 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, cla: yes

#529 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/S, lgtm, approved, cla: yes

#530 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, cla: yes
