Repository knative-extensions/sample-controller, pull requests merged in 2022-03, with the labels that each got.

#606 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#607 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved

#608 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#609 Add update crd to update-codegen process
  config/300-addressableservice.yaml
  config/300-simpledeployment.yaml
  hack/update-codegen.sh
Labels: size/M, lgtm, approved, ok-to-test, kind/cleanup

#610 Adding code of conduct to reference knative/community's CoC
  code-of-conduct.md
Labels: size/M, lgtm, approved

#612 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#615 set the right PATH during codegen
  hack/update-codegen.sh
  hack/update-k8s-deps.sh
Labels: size/M, lgtm, approved

#613 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL
