Repository knative-extensions/sample-controller, pull requests merged in 2024-01, with the labels that each got.

#828 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#830 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#831 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#832 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/samples/v1alpha1/addressableservice/reconciler.go
  pkg/client/injection/reconciler/samples/v1alpha1/simpledeployment/reconciler.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#825 Use go_run instead of run_go_tool
  hack/update-codegen.sh
Labels: size/XS, lgtm, approved, ok-to-test

#834 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#835 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#836 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/common/model/alert.go
  vendor/github.com/prometheus/common/model/metadata.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/github.com/prometheus/common/model/signature.go
  vendor/github.com/prometheus/common/model/silence.go
  vendor/github.com/prometheus/common/model/value.go
  vendor/github.com/prometheus/common/model/value_float.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/google.golang.org/protobuf/encoding/protodelim/protodelim.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#837 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#838 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#839 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#840 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved
