Repository knative-extensions/sample-controller, pull requests merged in 2025-03, with the labels that each got.

#942 :wastebasket: Remove cmd/schema usage
  cmd/schema/main.go
  go.mod
  go.sum
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/.mailmap
  vendor/github.com/spf13/cobra/CONDUCT.md
  vendor/github.com/spf13/cobra/CONTRIBUTING.md
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/MAINTAINERS
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/knative.dev/hack/schema/LICENSE
  vendor/knative.dev/hack/schema/commands/commands.go
  vendor/knative.dev/hack/schema/docs/docs.go
  vendor/knative.dev/hack/schema/registry/registry.go
  vendor/knative.dev/hack/schema/schema/generate_schema.go
  vendor/knative.dev/hack/schema/schema/json_schema_props.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, kind/removal

#944 :broom: Prepare for vendorless
  go.mod
  go.sum
  hack/add-boilerplate.sh
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/presubmit-tests.sh
  vendor/knative.dev/hack/boilerplate.go.txt
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L, kind/cleanup

#946 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
