Repository knative-extensions/sample-controller, pull requests merged in 2025-04, with the labels that each got.

#948 bump to golangci yaml v2
  .golangci.yaml
Labels: size/XS, lgtm, approved

#950 bump to golangci yaml v2
  .golangci.yaml
Labels: lgtm, approved, size/L

#949 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/M, lgtm, approved

#952 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#951 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/M, lgtm, approved

#953 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
